Update patch set 5
Patch Set 5:

interesting... there's a new failure here:

	InstallDexMetadataHostTest.testProfileSnapshotAfterInstall (com.android.cts.dexmetadata)

java.lang.AssertionError: array lengths differed, expected.length=58 actual.length=59
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.internal.ComparisonCriteria.assertArraysAreSameLength(ComparisonCriteria.java:76)
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:37)
	at org.junit.Assert.internalArrayEquals(Assert.java:532)
	at org.junit.Assert.assertArrayEquals(Assert.java:341)
	at org.junit.Assert.assertArrayEquals(Assert.java:352)
	at com.android.cts.dexmetadata.InstallDexMetadataHostTest.testProfileSnapshotAfterInstall(InstallDexMetadataHostTest.java:217)


    @Test
    public void testProfileSnapshotAfterInstall() throws Exception {
        assumeProfilesAreEnabled();

        // Install the app.
        new InstallMultiple().addApk(mApkBaseFile).addDm(mDmBaseFile).run();

        // Take a snapshot of the installed profile.
        String snapshotCmd = "cmd package snapshot-profile " + INSTALL_PACKAGE;
        String result = getDevice().executeShellCommand(snapshotCmd);
        assertTrue(result.trim().isEmpty());

        // Extract the profile bytes from the dex metadata and from the profile snapshot.
        byte[] snapshotProfileBytes = extractProfileSnapshotFromDevice();
        byte[] expectedProfileBytes = extractProfileFromDexMetadata(mDmBaseFile);

        assertArrayEquals(expectedProfileBytes, snapshotProfileBytes);
    }

+calin@ since i'm not sure whether we'd expect this to pass if we change the zip CRC. (the fact that the array is a different _size_ is a little worrying though...)

Patch-set: 5
CC: Gerrit User 1022077 <1022077@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1003224 <1003224@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0