Update patch set 1
Patch Set 1:

Hello there, Elliott

Thanks a lot for adding me, I will post comments inline.

> unfortunately it turns out that the libcore tests aren't in presubmit? looks like in addition to the NDK breakage (which is just because the NDK still needs to support non-Neon, and is easily worked around), the zlib optimizations break a bunch of libcore tests.
> 

I would recommend to update to the ToT, as I've done some cleanups and refactorings in the CPU features detection code and we should better handle now the scenario where no NEON/SIMD optimizations are enabled.

> they sound pretty scary:
> 
>   org.apache.harmony.tests.java.util.zip.DeflaterTest#test_ConstructorIZ
>     junit.framework.AssertionFailedError: final decompressed data contained more bytes than original - constructorIZ expected:<0> but was:<85>
> 
> ...but when you actually look at the test, they're not actually looking at how many bytes the inflater claims to have returned. (and are surprised to see that the inflater has actually touched more bytes than expected in the output array.)
> 
>         byte outPutInf[] = new byte[500];
>         Inflater infl = new Inflater(true);
>         while (!infl.finished()) {
>             if (infl.needsInput()) {
>                 infl.setInput(outPutBuf);
>             }
>             infl.inflate(outPutInf);
>         }
>         for (int i = 0; i < byteArray.length; i++) {
>             assertEquals(byteArray[i], outPutInf[i]);
>         }
>         assertEquals("final decompressed data contained more bytes than original - constructorIZ",
>                 0, outPutInf[byteArray.length]);
> 
> (most failures appear to be copy & pastes of this, but there's also one where a deflate using the huffman strategy outputs 99 bytes instead of 100.)

This seems pretty similar to the case I've described we faced when inflate_chunk_copy was enabled (https://issuetracker.google.com/issues/115695768).

Quote: "The issue was with GMeet app Java code as it was relying on non-specified behavior of vanilla zlib (i.e. zero the whole input buffer) that has changed due to  the optimization (i.e. we may perform a long store and write some garbage at the end of the buffer, but we keep track of the correct size of decompressed content and also ensure we got enough room to perform the write).".

Just as an experiment, try to enable only CRC32, Adler-32 and read64 optimizations but *not* inflate_chunk_copy (i.e. INFLATE_CHUNK_SIMD_NEON) and see what is the output of the tests.

Since I'm back from vacations, I should have time to help out on this one.
:-)

Patch-set: 1
Reviewer: Gerrit User 1512829 <1512829@85c56323-6fa9-3386-8a01-6480fb634889>